### ISSUE TITLE
Clean up compiler warnings

### ISSUE THREAD

**Issue by lprimak** [apache/shiro#1004]
Currently, there around 300 warnings in the code, they should be cleaned up

**Comment by bmarwell** [comment]
We can add -processing as a start

**Comment by seanpmcn** [comment]
Which warnings does this issue refer to, because there is a different amount depending on what you're looking at.

**Comment by lprimak** [comment]
Get the simple stuff done first. Leave more complicated stuff for later

**Comment by lprimak** [comment]
Hi, @seanpmcn 
Do you have an update?
Thank you

**Comment by seanpmcn** [comment]
@lprimak 
Sorry about the lack of update.
I got caught up in work for grad school. I think I may need to step back from this one and let others take care of it.

I hope that's alright. I'm still getting used to the etiquette and protocols of open source.

**Comment by lprimak** [comment]
That's not a problem. You are welcome to pick up issues when you can.
