### ISSUE TITLE
Expand checkstyle to all modules (root)

### ISSUE THREAD

**Issue by lprimak** [apache/shiro#1005]
Currently, only Jakarta EE module has checkstyle enabled.
Need to enable checkstyle on root module, so it encompasses all modules.
Of course, this requires that all modules comply with the checkstyle rules.
This needs to be done as well.

**Comment by fpapon** [comment]
Just a warning, if we want to enable checkstyle, we could have a lot of code source update to do.

**Comment by EdgarRamirezFuentes** [comment]
Hi, guys!
I'm new in this world of Java, but I would like to keep contributing  to this project.
If you guide through this issue, I am willing to learn and do the research to help in this project. :D

**Comment by bmarwell** [comment]
Hi @EdgarRamirezFuentes 

Probably an `inherit` parameter is enough between the version and the config right here: https://github.com/apache/shiro/blob/main/pom.xml#L543-L546

But haven't looked into it, as I am in a rush right now.

If it works, you should get a message that checkstyle was executed for every module when running `mvn verify` on Shiro. It will probably break something too.

If you get to that point, create the PR and point out what did break and why. If there's just small fixes needed (eg whitespace changes), just do a second commit with the fixes. In any other case, we *might* want to exclude some modules from checking or just do a big "fix up all" commit and add it to [a special ignore file](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view). Yes, the commit to that file needs to be a separate one. :) 

HTH to get you started!

**Comment by lprimak** [comment]
> Probably an inherit parameter

Please disregard the above (sorry, that's incorrect @bmarwell :)

Instead, move the section mentioning the checkstyle plugin from https://github.com/apache/shiro/blob/d627bf677a757de6c917e96024fbe46e07b34364/integration-tests/jakarta-ee/pom.xml#L472 to the `<plugin>` section of the root pom.
This will activate checkstyle at the root level, and as you might have guessed, break a lot of things because they don't conform to checkstyle rules :)
Those would need to be fixed as they come up.

Once again, thank you!

**Comment by bmarwell** [comment]
Yes, I caught the plugin management section. Oops.

**Comment by EdgarRamirezFuentes** [comment]
@lprimak @bmarwell I hope you're having a nice day!
I moved the checkstyle to the root pom, and as it was expected... it broke a lot of things.
In the PR i added photos but idk why github does not show them.
Anyways, I'll be working on fixing some of the code that does not fulfill the checkstyle rules, and i'll commit those changes.

**Comment by damonxue** [comment]
pls assign 2 me.

**Comment by lprimak** [comment]
@EdgarRamirezFuentes What do you think about below?

> pls assign 2 me.

**Comment by EdgarRamirezFuentes** [comment]
@lprimak Sure! I have no problem about it. 
At this moment it's kinda hard to me to contribute to the project. So, It would be nice if @damonxue helps us to fix this issue.

**Comment by lprimak** [comment]
Done. @EdgarRamirezFuentes Can you give @damonxue permissions to your PR?
Alternatively, Damon can create your own.

**Comment by damonxue** [comment]
> Done. @EdgarRamirezFuentes Can you give @damonxue permissions to your PR?
> 
> Alternatively, Damon can create your own.

Pls wait for me, I will done a task in Apache Shenyu in a week,and then do this.

**Comment by damonxue** [comment]
@lprimak  Pls review.
