### ISSUE TITLE
[Enhancement] Upgrade Shiro to htmlunit 3.3.0 or higher

### ISSUE THREAD

**Issue by lprimak** [apache/shiro#1010]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

HtmlUnit 2.x is EOL.
Need to update to HtmlUnit 3.x as described below:
https://github.com/HtmlUnit/htmlunit/releases/tag/3.3.0

### Describe the solution you'd like

Self-expanatory

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by bmarwell** [comment]
If it was not so much work, I'd say use JSoup... but that may be for another day.

**Comment by lprimak** [comment]
Seems simple just to upgrade, but I am not opposed to jsoup either
