### ISSUE TITLE
[Feature] BOM for the non-Jakarta version of Shiro

### ISSUE THREAD

**Issue by boris-petrov** [apache/shiro#1015]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

BOMs are useful for version-deduplication and for using the same version of all Shiro packages. A BOM for the Jakarta version of Shiro exists for 1.12.0 but not for the javax one. It would be nice to also add it. It seems to me that there was one in version 1.11.0.

[Another discussion](https://github.com/apache/shiro/issues/1014).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lprimak** [comment]
@boris-petrov are you sure that there was one for 1.11?  I don’t think anyone removed any BOM elements in 1.12 …

**Comment by lprimak** [comment]
I thought about this a bit, and I am not sure how a BOM for non-jakarta (javax) artifacts would help.
The only reason there *is* a BOM for Jakarta is that every Shiro artifact has to have exclusions and needs to be individually included by application developer. In that specific case, BOM is very helpful and eases dependency inclusion.

However, for non-Jakarta (javax), all Shiro artifacts have their dependencies included already as transitive,
so there is no need to include all of them, just the most high-level one you use.

What do you think? Can you give a specific example (reproducer?) where a BOM would be actually useful?

**Comment by lprimak** [comment]
Ok, I think we are going in circles here... I am going to reopen your original issue.
It's clear that you don't need a non-Jakarta BOM and trying to figure out some specific poblem you are having.

**Comment by boris-petrov** [comment]
@lprimak I answered in the issue a bit more but here I wanted to ask about this specific thing you said:

> The only reason there is a BOM for Jakarta is that every Shiro artifact has to have exclusions and needs to be individually included by application developer. ... However, for non-Jakarta (javax), all Shiro artifacts have their dependencies included already as transitive, so there is no need to include all of them, just the most high-level one you use.

I'm not sure I understand. Do you mean that when I'm using the Jakarta version of Shiro I have to add *both* `shiro-web` and `shiro-core` explicitly (even though the former depends on the latter)? But that's not the case for the javax version? And that's the reason you've added the BOM? If so... why? I don't understand what does Jakarta vs javax have to do with the way dependencies are managed?

**Comment by lprimak** [comment]
> Do you mean that when I'm using the Jakarta version of Shiro I have to add both shiro-web and shiro-core explicitly

Yes, that's exactly what I mean. I don't want to go into too great of detail about this (you can read the maven docs if you want).
Shiro documentation specifies exactly this: https://shiro.apache.org/jakarta-ee.html
Scroll down a bit to see the maven dependency section.

**Comment by boris-petrov** [comment]
It's kind of funny that we talk in two different threads. :smile: I see in this link how to use Shiro on Jakarta but it doesn't really say *why* that's the case. Am I missing it somewhere? Could you briefly explain why the javax version specifies correct transitive dependencies but the Jakarta version doesn't? Is it because of [this](https://issues.apache.org/jira/browse/SHIRO-632)? Sorry for taking so much of your time, I'm just curious what had to change and why.

**Comment by fpapon** [comment]
@boris-petrov we are using the maven-shade-plugin to generate the jakarta jars, the plugin update the import dependencies in the generated byte code but the maven pom dependencies are not updated. This why we need to specify the jarkarta classifier to link the jakarta modules between them. The BOM is a helper to not do this manually.
Last thing, we only generate jakarta jars for the module that are using javax namespace, the other are not.

**Comment by lprimak** [comment]
In addition to what @fpapon said, the maven POM model is not capable of handling transitive dependencies with with classifiers. This is why the BOM is necessary for Jakarta artifacts.

Shiro project is simple enough not to need a BOM in the first place, as everything is handled well by plain maven transitive dependency mechanism (excluding Jakarta).
This is why the BO is not there, and not needed.
