### ISSUE TITLE
how to change the httponly of the removeFrom method in SimpleCookie to true

### ISSUE THREAD

**Issue by LiJunYi2** [apache/shiro#1034]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

<img width="1260" alt="image" src="https://github.com/apache/shiro/assets/40384503/b78843b5-e80b-4a7c-8e7f-227b356af6d7">

Please help me, I change how to change the httponly of the removeFrom method in SimpleCookie to true

**Comment by lprimak** [comment]
Why? As comment clearly states the cookie removal is insensitive to this.

**Comment by LiJunYi2** [comment]
> Why? As comment clearly states the cookie removal is insensitive to this. You can subclass override the method if necessary, but I don't believe it is.

But, the contrast security scan reported a high-risk vulnerability, and we could not set httponly to true to fix it

**Comment by lprimak** [comment]
The scan report is clearly invalid.

**Comment by LiJunYi2** [comment]
> The scan report is clearly invalid.

I think so too, but the boss only looks at the report, so is there a way to set it?

**Comment by lprimak** [comment]
I don't think this can be easily done at all. I guess subclass SimpleCookie and all references to it :)

**Comment by LiJunYi2** [comment]
> I don't think this can be easily done at all. I guess subclass SimpleCookie and all references to it :)

All right, I'll find another way. Thank you for your reply
