### ISSUE TITLE
[Question]PermissionAnnotationHandler.java line 81~86

### ISSUE THREAD

**Issue by xian1295004710** [apache/shiro#1057]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

![image](https://github.com/apache/shiro/assets/143772347/7adcc344-1d3f-4fa4-bc9b-85b94df55e80)
I think there is a bug in these lines,but I can not make sure.
I think variable 'hasAtLeastOnePermission'  always equals to 'getSubject().isPermitted(perms[perms.length-1])', is this result a bug?

**Comment by lprimak** [comment]
I don't see how... the variable is set to true only if any permission is present... hence the variable name.
Am I not seeing something you are seeing? In my view it looks like it works as designed

**Comment by fpapon** [comment]
@xian1295004710 HasAtLeastOnePermission is always = true only for the latest valid permission of the list, if a check is false, the variable is not set, I think this is your misunderstanding.

The logic is that if we don't find any permitted permission in the list, we check the first permission to raise an error with a message related to the check.

Side note: We can optimize a little by adding a break into the loop after setting **hasAtLeatOnePermission** to true.

**Comment by xian1295004710** [comment]
@lprimak @fpapon Thank you for taking time to answer the question very much.  I am a newbie. I feel very embarrassed about that misunderstanding, I could run a test by myself, but I was too confident to ask that silly question, which  makes your precious time wasted.  I hope you don't mind.

**Comment by lprimak** [comment]
> I feel very embarrassed 

Absolutely no need. Your question prompted the cleanup of the code, it was indeed confusing, so thank you for your contribution!

Always ask questions!

**Comment by fpapon** [comment]
@xian1295004710 don't worry, there is no stupid question! Thank you for asking and using Apache Shiro!
We hope you will add your first contribution soon :)
Don't hesitate!

**Comment by xian1295004710** [comment]
I'm very glad to hear that (^o^), and thanks for your encouragement. It could make my day!
