### ISSUE TITLE
commons-beanutils  upgrade

### ISSUE THREAD

**Issue by zhanyao** [apache/shiro#1107]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

<dependency>
  <groupId>org.apache.commons</groupId>
  <artifactId>commons-beanutils</artifactId>
</dependency>

### Describe the solution you'd like

<dependency>
  <groupId>org.apache.commons</groupId>
  <artifactId>commons-beanutils2</artifactId>
  <version>2.0.0</version>
</dependency>

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lprimak** [comment]
A Pull Request would be appreciated.

**Comment by lprimak** [comment]
Unfortunately, commons-beanutil2 has not been released. According to official pages (https://commons.apache.org/proper/commons-beanutils/download_beanutils.cgi), the latest version still 1.9.4.
However, looks like they are actively working on 2.0 and when it's released you can reopen this issue, or raise another one.

**Comment by sepe81** [comment]
@lprimak Would it be an option to use the variant from com.melloware:commons-beanutils2 as seen in [this pull request](https://github.com/TIBCOSoftware/jasperreports/pull/488)?

**Comment by lprimak** [comment]
That's a rather drastic step for a low-priority issue.
See https://issues.apache.org/jira/projects/BEANUTILS/issues/BEANUTILS-532
and add your vote / comments
