### ISSUE TITLE
spring boot 2.x End of Support is 2023-11-24,  it is coming, suggest shiro 2 directly upgrade to spring boot 3

### ISSUE THREAD

**Issue by mizhousoft** [apache/shiro#1125]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

spring boot 2 will no longer maintain, there may be bug or security

![image](https://github.com/apache/shiro/assets/4065604/14a5de31-20db-4c56-a542-f13a1af01cc2)

**Comment by lprimak** [comment]
SprintBoot 3 is already supported by Shiro 2.0

**Comment by matthew-a-carr** [comment]
@lprimak Please could you give a bit more clarity around the stability of Shiro 2.0 given it is in Alpha and when the project is planning on making 2.0 the current release? 

The current release on the [Shiro website](https://shiro.apache.org/documentation.html) and in [GitHub is 1.13.0](https://github.com/apache/shiro/releases/tag/shiro-root-1.13.0)

<img width="461" alt="image" src="https://github.com/apache/shiro/assets/76042279/2dd2ca72-6809-46f7-b6b2-bf8577f4635d">

**Comment by lprimak** [comment]
As far as I understand, the only reason Shiro 2 is still in alpha is that the new encryption algorithm documentation is not done quite yet.
As far as other facets of 2.0, I think it's stable enough for release.
Perhaps other members could shine more light on it more than I can.

**Comment by matthew-a-carr** [comment]
Thanks for the update @lprimak.  

Is there an ETA on when this will become the most recent version?

<img width="774" alt="image" src="https://github.com/apache/shiro/assets/76042279/8bae0cbb-54f9-4f59-916b-7bdd6d55dd72">
