### ISSUE TITLE
[Question] Compatibility Issue with Spring Boot 3.2 and Shiro 2.0.0

### ISSUE THREAD

**Issue by hadesy** [apache/shiro#1178]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

I'm running into issues with Spring Boot 3.2 and Shiro 2.0.0-alpha-4. The Spring Boot guide (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee) says javax.servlet is now jakarta.servlet, but Shiro is still on javax.servlet. Does this mean we need to update  dependencies?

**Comment by fpapon** [comment]
@hadesy you need to use the dedicated Shiro shaded jar from the BOM with the `jakarta` classifier:

https://github.com/apache/shiro/blob/82d47384ac40c95da19e0630ca77b6b131dbd846/bom/pom.xml#L91
