### ISSUE TITLE
Redirect users to access deny page if they do not have specific role

### ISSUE THREAD

**Issue by samsonsouley** [apache/shiro#1179]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

Hello all,
I am using Apache shiro 1.11.0 and i want to understand something.
I have to redirect user which do not have specific role to the access deny page.
What i have done is, as every page has it own managedbean and roles are base on page, i put a code in the constuctor of every managed bean which check if the  user has permission or not. If not it redirect him to the accessdenided page. The problem it rendred first the page before it redirect the user to the access denied page.
I found this topic [https://andy722.wordpress.com/2014/01/27/make-apache-shiro-allow-several-roles-to-access-resource/](url) on internet which show how we can do it. I have done the same and remove the checking in the constructor and the user still have access.
Somebody can help me understand and help me?

**Comment by bdemers** [comment]
My guess is you need to make sure users have access to your access denied page (and you shouldn't need any custom code in your beans)?

Maybe something like:

```ini
[main]
...
shiro.unauthorizedUrl = /access-denied

[urls]
...
/protected-page = roles["role1,role2"]
/access-denied = authc
```

Users would need to be authenticated to view this page.

This is just a guess, if this doesn't help you please point us to an example project we can take a look at it.

**Comment by bdemers** [comment]
@samsonsouley Awesome!
Thanks for following up with us!
