### ISSUE TITLE
[Bug] Run time dependencies missing from shiro-web 1.13.0 karaf feature

### ISSUE THREAD

**Issue by steinarb** [apache/shiro#1300]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Environment

Apache karaf 4.4.5, java 17.0.9, debian 12.4 "bookworm", amd64

### Shiro version

1.13.0

### What was the actual outcome?

It was necessary to [add the missing bundles in my own feature](https://github.com/steinarb/authservice/blob/master/authservice/authservice.web.security/src/main/feature/feature.xml#L7) to get things to load and run.

In addition to the bundles loaded by me above, ie:
```
        <bundle start-level="80">mvn:commons-beanutils/commons-beanutils/1.9.3</bundle>
        <bundle start-level="80">mvn:commons-collections/commons-collections/3.2.2</bundle>
```
someone else said [today he needed this one as well](https://lists.apache.org/thread/k61scho1d2tmmp92sklyk9njr8m6wmrr):
```
   mvn:org.apache.shiro/shiro-config-core/1.13.0
```

### What was the expected outcome?

That the shiro-web karaf feature had provided all features necessary to start and run.

### How to reproduce

Load the shiro-web feature into karaf and try to do something with it

**Comment by lprimak** [comment]
Since 1.x branch is only maintained for critical issues, and this is fixed in 2.x, I will close this issue.
Feel free to reopen if there is something I am missing or this is still needed somehow
