### ISSUE TITLE
[Question] Ldap search filters escape Attributes

### ISSUE THREAD

**Issue by Reamer** [apache/shiro#1329]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

The Apache Zeppelin project uses Shiro as a security framework. I am aware that Zeppelin uses Shiro a little incorrectly, but that is not the issue.
Recently the following pull request https://github.com/apache/zeppelin/pull/4714 has been opened and I was wondering why this is not implemented in the security framework Shiro. What do you think? Does it make sense to perhaps include the code snippet in the Shiro project?

**Comment by bdemers** [comment]
Thanks for reaching out @Reamer!

In Shiro's LDAP realms, the filters are set at configuration time (e.g. a config file), it's expected configuration is formatted correctly.  If these values were the results of user inputs (outside of Shiro's control), they should be escaped if needed.

Shiro doesn't concatenate strings when performing LDAP searches, so unvalidated inputs (such as usernames) _shouldn't_ need to be escaped, as the lower level APIs .

If you think I'm wrong or am missing something, please let us know!
However, given that this issue relates to injection attacks, please use the proper channels when reporting potential security issues.

You can read an overview of how to report an issue at Apache: https://www.apache.org/security/
Or an abbreviated page in the Shiro: https://shiro.apache.org/security-reports.html#reporting_a_vulnerability

**TL;DR**: Email [security@shiro.apache.org](mailto:security@shiro.apache.org).

---

[How to report a vulnerability: Responsible Disclosure for Developers](http://www.youtube.com/watch?v=Mh_fivNC8Wk) 
This video explains how and why security issues require special handling. 
[![How to report a vulnerability: Responsible Disclosure for Developers](http://img.youtube.com/vi/Mh_fivNC8Wk/0.jpg)](http://www.youtube.com/watch?v=Mh_fivNC8Wk)
