### ISSUE TITLE
[Bug] Ini.java missing from 1.13.0 shiro-core maven source attachment

### ISSUE THREAD

**Issue by steinarb** [apache/shiro#1345]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Environment

debian 12.5 "bookworm", amd64, openjdk-17-jdk:amd64  17.0.10+7-1~deb12u1, maven 3.8.7-1, eclipse IDE 2023-03 (4.27.0)

### Shiro version

1.13.0

### What was the actual outcome?

When debugging, eclipse couldn't find the source for the Ini class, and reported: 

The source attachment does not contain the source for the file Ini.class

And looking into the ~/.m2/repository/org/apache/shiro/shiro-core/1.13.0/shiro-core-1.13.0-sources.jar the Ini.java file is indeed missing and probably some others too.

### What was the expected outcome?

I should have seen the source for the Ini class in the eclipse debugger.

### How to reproduce

Open a maven project that uses shiro-core 1.13.0 as a maven dependency and try navigating into the Ini class.

**Comment by steinarb** [comment]
I think I see what the problem is: duplicate package org.apache.shiro.config

The package org.apache.shiro.config can be found in both shiro-core-1.13.0.jar and shiro-config-core-1.13.0.jar and only shiro-config-core has Ini.java in its source attachment.  So when Ini.class is found from shiro-core, eclipse can't find the source.

**Comment by lprimak** [comment]
This cannot be fixed in a compatible way in Shiro 1
Shiro 2 fixes this
