### ISSUE TITLE
[Regression] commons-configuration2 is pulled in as a required dependency

### ISSUE THREAD

**Issue by papegaaij** [apache/shiro#1352]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Environment

This is a dependency of shiro-core, so it's for every environment.

### Shiro version

2.0.0

### Regression from:
1.13.0

### What was the actual outcome?

Observe `commons-configuration2` in the output below:
```papegaaij@papegaaij:~$ mvn -f ~/.m2/repository/org/apache/shiro/shiro-core/2.0.0/shiro-core-2.0.0.pom dependency:tree -Dscope=compile
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< org.apache.shiro:shiro-core >---------------------
[INFO] Building Apache Shiro :: Core 2.0.0
[INFO]   from shiro-core-2.0.0.pom
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO] 
[INFO] --- dependency:3.6.1:tree (default-cli) @ shiro-core ---
[INFO] org.apache.shiro:shiro-core:bundle:2.0.0
[INFO] +- org.apache.shiro:shiro-lang:jar:2.0.0:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.12:compile
[INFO] +- org.apache.shiro:shiro-cache:jar:2.0.0:compile
[INFO] +- org.apache.shiro:shiro-crypto-hash:jar:2.0.0:compile
[INFO] |  +- org.apache.shiro:shiro-crypto-core:jar:2.0.0:compile
[INFO] |  \- org.bouncycastle:bcprov-jdk18on:jar:1.77:compile
[INFO] +- org.apache.shiro:shiro-crypto-cipher:jar:2.0.0:compile
[INFO] +- org.apache.shiro:shiro-config-core:jar:2.0.0:compile
[INFO] +- org.apache.shiro:shiro-config-ogdl:jar:2.0.0:compile
[INFO] |  \- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |     \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] +- org.apache.shiro:shiro-event:jar:2.0.0:compile
[INFO] +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:provided
[INFO] \- org.apache.commons:commons-configuration2:jar:2.9.0:compile
[INFO]    +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO]    \- org.apache.commons:commons-text:jar:1.10.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.969 s
[INFO] Finished at: 2024-03-11T21:48:45+01:00
[INFO] ------------------------------------------------------------------------
```

### What was the expected outcome?

Commons-configuration2 should be made optional. The code here already supports it being optional:
https://github.com/apache/shiro/blob/36cad481dd1f58f7f0263981d7f4a61dd39dbd8c/config/ogdl/src/main/java/org/apache/shiro/config/ogdl/ReflectionBuilder.java#L782-L789

### How to reproduce

see above

**Comment by lprimak** [comment]
I am not certain this is a bug. I believe the code started as optional, but later became required, but the optionality was not removed from the code.
IMHO it would be too much of a risk to make it optional at this time, because it would mysteriously break functionality existing applications currently rely on and require inclusions of explicit additional dependency for existing applications.

**Comment by lprimak** [comment]
Maybe someone else can chime in?

**Comment by fpapon** [comment]
I think this is a bug, I will go deeper.

It's well optional on `config-ogdl`:
https://github.com/apache/shiro/blob/9507f2476d6875f1ab07df0fc0155a062c85fb2c/config/ogdl/pom.xml#L97

But not in `core`:
https://github.com/apache/shiro/blob/9507f2476d6875f1ab07df0fc0155a062c85fb2c/core/pom.xml#L147

**Comment by lprimak** [comment]
Maybe not a bug but a code smell? Perhaps the required dependency should be moved into `ogdl` and removed from `core` but net effect wouldn't change

**Comment by fpapon** [comment]
@lprimak the problem was introduced in this commit:
https://github.com/apache/shiro/commit/57557212447257b83c13122c5ae93e028d5e3e19

Can you explain why adding a provided dependency because of compiler warning?

**Comment by lprimak** [comment]
I remember... it's an OSGi warning from the bnd plugin

**Comment by lprimak** [comment]
I will try a PR to fix it then... thanks for your research @fpapon

**Comment by fpapon** [comment]
May be just adding the dependency in `optional` scope will be enough

**Comment by fpapon** [comment]
The warning from the bnd plugin comes from these lines:
https://github.com/apache/shiro/blob/9507f2476d6875f1ab07df0fc0155a062c85fb2c/core/pom.xml#L82

I will make some test in Karaf to see why we need them. I think we don't need to add these import package because we are not using them.

**Comment by lprimak** [comment]
No need. Making it optional in core worked and there is no warning

**Comment by lprimak** [comment]
@papegaaij Thank you for the report! This snuck in during build / code cleanup

**Comment by papegaaij** [comment]
No problem. I just happen to notice it because commons-configuration2 triggered a failure due to its dependency on a javax API. Thanks for fixing this!
