### ISSUE TITLE
[Question] 2.0.1 Release Time?

### ISSUE THREAD

**Issue by wenjunzhangp** [apache/shiro#1378]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

Hello, version 2.0.1 will support Java 17 or 21. I would like to know approximately when 2.0.1 will be released as I really need it

**Comment by wenjunzhangp** [comment]
Thanks for your kind attention and look forward your prompt reply.
thx~

**Comment by lprimak** [comment]
All released Shiro versions currently support Java 17 and 21, including 1.x and 2.x
