### ISSUE TITLE
[Enhancement] Remove Quartz module

### ISSUE THREAD

**Issue by lprimak** [apache/shiro#1499]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Quartz module has been abandoned. It needs to be removed

### Describe the solution you'd like

Remove quartz from Shiro

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by himakar579** [comment]
Hi Iprimak, May i know details of this task. I am Beginner and i would like to contribute on opensource projects

**Comment by 555vedant** [comment]
what is update of this issue i would like to work on it if still has some enhacement ??

**Comment by lprimak** [comment]
Will wait for @Himakar to finish this.
It can't go until 3.x anyway so no rush

**Comment by Himakar** [comment]
@lprimak, I have done the required changes and Pushed the updated code.

**Comment by lprimak** [comment]
Sorry, @Himakar 
Can you please check the (review) comments on the PR again. There are 3 issues still unresolved.

And thank you for your contributions!

**Comment by Himakar** [comment]
Hi @lprimak,
Sorry for late reply, I have done the required changes and created new pull request. If still any changes required from end. Please let me know. Thanks!!

**Comment by fpapon** [comment]
@Himakar Thanks for your contribution!

**Comment by lprimak** [comment]
Looks like Quartz has been resurrected. I will revert these changes
