### ISSUE TITLE
Migration 1.13 -> 2.0.x guide?

### ISSUE THREAD

**Issue by goodale** [apache/shiro#1589]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

Updating from 1.13 to 2.x on an existing project yields compiler errors.  I searched but have not found a migration guide and I'd like to make sure the presumed changes are correct.  

Is there a guide available?  

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lprimak** [comment]
Unfortunately, there is no migration guide currently.
You can refer to individual issues in the Release Notes: https://github.com/apache/shiro/releases/tag/shiro-root-2.0.0

If you would like to contribute your findings, we would welcome that.
Or, if you have any specific questions, you can ask them on the mailing list of slack.

**Comment by goodale** [comment]
thank you.  I'll try and compile some notes when I have a chance to work on
the migration and will be happy to share them.

**Comment by lukasalexanderweber** [comment]
@goodale have you successfully migrated and have shared your notes / a guide somewhere?
