### ISSUE TITLE
[Doc] Some documentations link lead to Not Found

### ISSUE THREAD

**Issue by seung-00** [apache/shiro#1692]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

Hi,
I have found that links under the path `shiro.apache.org/static/current/apidocs/org/apache/shiro` and `shiro.apache.org/static/2.0.0/apidocs` are inaccessible, referenced in the documentation. Here are some examples:

* [org.apache.shiro.realm.text.IniRealm](https://shiro.apache.org/static/current/apidocs/org/apache/shiro/realm/text/IniRealm.html) from [this page](https://shiro.apache.org/configuration.html#:~:text=Just%20defining%20non%2Dempty%20%5Busers%5D%20or%20%5Broles%5D%20sections%20will%20automatically%20trigger%20the%20creation%20of%20an%20org.apache.shiro.realm.text.IniRealm%20instance%20and%20make%20it%20available%20in%20the%20%5Bmain%5D%20section%20under%20the%20name%20iniRealm.%20You%20can%20configure%20it%20like%20any%20other%20object%20as%20described%20above.)
* [HashedCredentialsMatcher JavaDoc](https://shiro.apache.org/static/current/apidocs/org/apache/shiro/authc/credential/HashedCredentialsMatcher.html) from [this page](https://shiro.apache.org/realm.html#:~:text=definitely%20read%20the-,HashedCredentialsMatcher%20JavaDoc,-which%20covers%20these)
* [UsernamePasswordToken](https://shiro.apache.org/static/current/apidocs/org/apache/shiro/authc/UsernamePasswordToken.html) from [this page](https://shiro.apache.org/java-authentication-guide.html#:~:text=In%20this%20particular%20case%2C%20we%E2%80%99re%20using%20a%20class%20called%20UsernamePasswordToken.%20It%20is%20the%20most%20common%20authentication%20token%20used%20in%20the%20framework.)
* ...

Can anyone help look into this? Thanks.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lprimak** [comment]
Thank you for your report
In the future, please open documentation issues at https://github.com/apache/shiro-site/issues

Thanks!

**Comment by lprimak** [comment]
The documentation has now been fixed.
Thank you for reporting this!
