### ISSUE TITLE
[Question]HttpSession constructor argument cannot be an instance of ShiroHttpSession.  This is enforced to prevent circular dependencies and infinite loops.

### ISSUE THREAD

**Issue by iarora-rcc** [apache/shiro#1893]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

I am getting this issue in my spring boot app, which uses Shiro for session management. Earlier it was a EKS based app directly talking with the Load balancer. Now we are planning to add a API Gateway [krakend](https://www.krakend.io) API gateway to monitor API calls reaching my backend server. The app was working fine , however, now it is giving us above mentioned issue. 
I am getting this issue while calling the below line: 
`            Session userSession = new HttpServletSession(request.getSession(), ipAddress);
`

**Comment by lprimak** [comment]
Hi,

There is not nearly enough information here to even begin to answer your question.
I can only guess that you should probably use `request.getSession()` directly and not instantiate `HttpServletSession`

**Comment by iarora-rcc** [comment]
Hi @lprimak
thanks for a prompt reply.  I actually ran the API Gateway in local and things were working fine in terms of routing. Let me see , how can I solve it.
