### ISSUE TITLE
Build and test for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [apache/shiro#1928]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

## Description  
For aarch64 platform, I have built "Shiro " from source.  
 
## Steps   
Following STEPS (https://shiro.apache.org/10-minute-tutorial.html) were used for the building and installation: 

```
sudo apt-get install openjdk-11-jdk -y 
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64
export PATH=$PATH:$JAVA_HOME/bin
sudo apt install maven
```
## Outcome  

To validate that the build was successful we ran tests that were generated using "./mvnw clean install" command. All the tests ran successfully.   
All this information is also added to ARM Dashboard Software Ecosystem Dashboard for Arm (https://www.arm.com/developer-hub/ecosystem-dashboard/

**Comment by bdemers** [comment]
Thanks for reaching out @odidev!

We test Shiro on Linux, Windows, and Mac, nothing should be arch specific. But if you are interested in donating arm resources (or money to purchase them) to the ASF for us to run more builds with, you can do so here: https://donate.apache.org/
