### ISSUE TITLE
[Enhancement] bouncy castle's jar package is too large

### ISSUE THREAD

**Issue by hadongjing** [apache/shiro#1931]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

bouncy castle's jar package is too large, can we use a smaller package or some codes to meet the hash needs

### Describe the solution you'd like

replace bouncy castle with lightweight package or codes 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hadongjing** [comment]
![Screenshot 2024-12-24 at 10-43-56 Code search results](https://github.com/user-attachments/assets/bd7a37bb-3081-4d80-89ad-b06828cd6e77)
It looks like we don't need the full bouncy castle package

**Comment by lprimak** [comment]
Hi,

Unfortunately "Large" is subjective. Currently, I really don't see the Shiro team taking this on.
We are willing to look at PRs that use another well-known security library, however.
For now, will close this as "unplanned" but if you are willing to work on it, you can reopen it.
