### ISSUE TITLE
spring boot 3.0+

### ISSUE THREAD

**Issue by sam2099** [apache/shiro#891]
Hi:

Thanks for great work.
when will be support spring boot 3.0+ ?

**Comment by lprimak** [comment]
I believe that if you use the Jakarta artifacts (see [docs](https://shiro.apache.org/jakarta-ee.html))  - How to use Jakarta 9+ (jakarta.* namespace) section,
current version of Shiro should work with SpringBoot 3

Disclaimer: I am not a user of Sprint Boot and did not test this.

**Comment by damingerdai** [comment]
it doesn't work for me

**Comment by lprimak** [comment]
@damingerdai I looked at your PR briefly, and I don't see it using `jakarta` classifiers of Shiro,
i.e. `<classifier>jakarta</classifier` or gradle equivalent.
Perhaps this is why "doesn't work for me"

**Comment by house0128** [comment]
@lprimak  Is akarta EE support starting from version 2.0.0? The file says version 1.11.0, but it doesn't.
![image](https://github.com/apache/shiro/assets/18210121/716f5a62-881e-4e27-a706-0ba904a8b7ab)
![image](https://github.com/apache/shiro/assets/18210121/801e5049-fdaa-4bbc-b2d1-f55c033b89c7)

**Comment by damingerdai** [comment]
> @damingerdai I looked at your PR briefly, and I don't see it using `jakarta` classifiers of Shiro, i.e. `<classifier>jakarta</classifier` or gradle equivalent. See https://shiro.apache.org/jakarta-ee.html "Using Jakarta namespace" section carefully. Perhaps this is why "doesn't work for me"

it seem look like shiro v2 doesn't use jakarta jar and i use gradle, it is not like maven. so your solution doesn't work for me.
i will try other way to fix it or wait shiro v2 using jakarta jar

**Comment by lprimak** [comment]
I think there is some confusion here between jakarta `classifier` and the `jakarta ee` module. Jakarta EE module, which is available only with Shiro 2.0+, is "Jakarta EE" integration and doesn't have anything to do with Spring Boot.

On the other hand, Jakarta EE `classifier` is there for `core`, `web` and other Shiro modules that depend on Jakarta EE, which are available with Shiro 1.x.

Spring Boot 3 integration is available in Shiro 1.x via jakarta `classifier`
Jakarta EE integration module is available for both Jakarta EE/Java EE 8, or Jakarta EE 9+ via jakarta `classifier`, but only in Shiro 2.x+

Hope this clears things up.

**Comment by lprimak** [comment]
I am 100% sure that gradle has support for classifiers. Here is what I found googling: https://stackoverflow.com/questions/70579181/gradle-dependency-with-test-classifier

**Comment by house0128** [comment]
@lprimak  Thanks.
I try this way:
`<dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-core</artifactId>
            <version>1.11.0</version>
            <classifier>jakarta</classifier>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-spring</artifactId>
            <version>1.11.0</version>
            <classifier>jakarta</classifier>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-ehcache</artifactId>
            <version>1.11.0</version>
            <classifier>jakarta</classifier>
        </dependency>`
        
        
        Then meet this  problem, when we integrated shiro and springboot, we customized some things like this
        
        
        `@Bean(name = "shiroFilter")
    public ShiroFilterFactoryBean shiroFilter(@Qualifier("securityManager") SecurityManager manager) {
        ShiroFilterFactoryBean bean = new ShiroFilterFactoryBean();
        bean.setSecurityManager(manager);
        bean.setLoginUrl("/api/xxxxxx");

        Map<String, Filter> filtersMap = bean.getFilters();
        filtersMap.put("authc", new CustomFormAuthenticationFilter());

        LinkedHashMap<String, String> filterChainDefinitionMap = new LinkedHashMap<>();
        filterChainDefinitionMap.put("/api/xxxxxx", "anon");
        bean.setFilterChainDefinitionMap(filterChainDefinitionMap);
        return bean;
    }
    
    public class CustomFormAuthenticationFilter extends FormAuthenticationFilter  {
    @Override
    protected boolean onAccessDenied(ServletRequest request, ServletResponse response) throws Exception {
        // Get current login user
        Subject subject = getSubject(request, response);
        if (subject.getPrincipal() == null) {
            ...........
            return false;
        } else {
            return true;
        }
    }
    `
    
    In spring2 is ok.But in spring3 doesn't.Because 
    
    Map<String, Filter> filtersMap = bean.getFilters();------->Filter is jakarta.servlet.Filter.
    
     filtersMap.put("authc", new CustomFormAuthenticationFilter()); ----->CustomFormAuthenticationFilter is javax.servlet.Filter
     
     Any idea?

**Comment by sam2099** [comment]
I try shiro version = `2.0.0-alpha-2 ` with Spring boot version=`3.0.6` , problem is `org.apache.shiro.spring.web.ShiroFilterFactoryBean` is only support `javax.servlet.Filter`, but Spring boot 3 need `jakarta.servlet.Filter`
```xml
<dependency>
      <groupId>org.apache.shiro</groupId>
      <artifactId>shiro-bom</artifactId>
      <version>2.0.0-alpha-2</version>
      <scope>import</scope>
      <type>pom</type>
  </dependency>
```
```xml
<dependency>
    <groupId>org.apache.shiro</groupId>
    <artifactId>shiro-jakarta-ee</artifactId>
    <classifier>jakarta</classifier>
</dependency>

<dependency>
    <groupId>org.apache.shiro</groupId>
    <artifactId>shiro-cdi</artifactId>
    <classifier>jakarta</classifier>
</dependency>

<dependency>
    <groupId>org.apache.shiro</groupId>
    <artifactId>shiro-core</artifactId>
    <classifier>jakarta</classifier>
</dependency>

<dependency>
    <groupId>org.apache.shiro</groupId>
    <artifactId>shiro-web</artifactId>
    <classifier>jakarta</classifier>
</dependency>
<dependency>
    <groupId>org.apache.shiro</groupId>
    <artifactId>shiro-spring-boot-starter</artifactId>
    <version>2.0.0-alpha-2</version>
</dependency>
```

Any idea?  
Thank you.

**Comment by fpapon** [comment]
@sam2099 you need to use the jakarta classifier for the Shiro Spring module also.
There is a shiro-spring jakarta module that depend on jakarta.

**Comment by fpapon** [comment]
I will check the shiro bom that we provided to see if we can add the spring stuff and add a Spring sample for jakarta as we already done with the web sample.

**Comment by house0128** [comment]
@lprimak  Thanks.
 I  try shiro version = 1.11.0 with Spring boot version=3.1.0 . 
`
<dependency>
    <groupId>org.apache.shiro</groupId>
    <artifactId>shiro-core</artifactId>
    <version>1.11.0</version>
    <classifier>jakarta</classifier>
</dependency>
<dependency>
    <groupId>org.apache.shiro</groupId>
    <artifactId>shiro-spring</artifactId>
    <version>1.11.0</version>
    <classifier>jakarta</classifier>
</dependency>
<dependency>
    <groupId>org.apache.shiro</groupId>
    <artifactId>shiro-web</artifactId>
    <version>1.11.0</version>
    <classifier>jakarta</classifier>
</dependency>
`


We implemented the FormAuthenticationFilter class, which currently reports an error. I checked the source code

![image](https://github.com/apache/shiro/assets/18210121/555942c1-e755-4edc-967d-d6c0e1a82201)

**Comment by lprimak** [comment]
> I will check the shiro bom that we provided to see if we can add the spring stuff and add a Spring sample for jakarta as we already done with the web sample.

@fpapon great idea! :)

@house0128 Can you elaborate on the "error" you are getting?
The screenshot you attached is irrelevant as the `jakarta` artifacts use the shade plugin to rename the javax dependencies to jakarta ones.

Also, it would be helpful to see the output of `mvn dependency:tree`
If I was to bet, the non-jakarta Shiro dependencies are still included and are interfering with jakarta ones.
Exclusions are needed to remove non-Jakarta dependencies.
This is what shiro-bom does for Jakarta EE support currently, although Spring is not included in it (yet!)

**Comment by lprimak** [comment]
Basically, this needs to happen:
- Include Shiro BOM as described in Jakarta EE docs:
```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-bom</artifactId>
            <version>${shiro.version}</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>
```

- Exclude non-Jakarta artifacts from Spring:
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.shiro</groupId>
                <artifactId>shiro-spring</artifactId>
                <classifier>jakarta</classifier>
                <version>${shiro.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.shiro</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>javax.servlet</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by house0128** [comment]
@lprimak  Thanks.
Maybe that's why it failed.
The screenshot you attached is irrelevant as the jakarta artifacts use the shade plugin to rename the javax dependencies to jakarta ones.


Here is our pseudocode：
`
import jakarta.servlet.Filter;

@Bean(name = "shiroFilter")
    public ShiroFilterFactoryBean shiroFilter(@Qualifier("securityManager") SecurityManager manager) {
        ShiroFilterFactoryBean bean = new ShiroFilterFactoryBean();
        bean.setSecurityManager(manager);
        bean.setLoginUrl("/api/xxxxxx");

        Map<String, Filter> filtersMap = bean.getFilters();
        filtersMap.put("authc", new CustomxxxxxFilter());

        LinkedHashMap<String, String> filterChainDefinitionMap = new LinkedHashMap<>();
        filterChainDefinitionMap.put("/api/xxxxxx", "anon");
        bean.setFilterChainDefinitionMap(filterChainDefinitionMap);
        return bean;
}



import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

public class CustomxxxxxFilter extends FormAuthenticationFilter {
    @Override
    protected boolean onAccessDenied(ServletRequest request, ServletResponse response) throws Exception {
        Subject subject = getSubject(request, response);
        xxxxxxxxx
    }

    @Override
    protected boolean isAccessAllowed(ServletRequest request, ServletResponse response, Object mappedValue) {
        boolean allowed = super.isAccessAllowed(request, response, mappedValue);
        xxxxxxx
    }
}
`
I run mvn dependency:tree, there is indeed no reference to javax.server-api jar


We encountered compilation errors

Map<String, Filter> filtersMap = bean.getFilters();------------》Filter is  jakarta.servlet.Filter
filtersMap.put("authc", new CustomxxxxxFilter());-------》CustomxxxxxFilter is  javax.servlet.Filter

protected boolean onAccessDenied(ServletRequest request, ServletResponse response) throws Exception {----》request is  jakarta.servlet.ServletRequest
    Subject subject = getSubject(request, response);--------》request is  javax.servlet.ServletRequest

**Comment by lprimak** [comment]
@house0128 Did you follow the recommendations I just made above? https://github.com/apache/shiro/issues/891#issuecomment-1581192622

Remember, I am not a Spring user.
Pseudo-code and no "real" dependency:tree output is not very helpful, because I have to guess at the cause instead of looking at it directly.
A complete reproducer and real output would be much more helpful.

In any case, it's jot just the lack of `javax.servlet` package that's necessary.
What's necessary it to _only_ include the Shiro packages with `jakarta` classifier, and make sure none of the non-`jakarta`-classifier Shiro JARs (shiro-core, etc) are included.

The compilation errors are indicative of non-jakarta-classifier Shiro artifacts being included.

**Comment by damingerdai** [comment]
my question is like @[house0128](https://github.com/house0128), but i use gradle but he uses maven, so #891 (comment) does't work for me.
i try to use https://stackoverflow.com/questions/70579181/gradle-dependency-with-test-classifier to fix my issues, but it is sad

**Comment by lprimak** [comment]
@damingerdai https://github.com/apache/shiro/issues/891#issuecomment-1581192622 will absolutely work for you, you just need to translate it into what gradle understands.
I am not a gradle user so I can't really help with that either.

**Comment by house0128** [comment]
@lprimak  Does shiro only support Jakarta 9+ but not 10?
I use  tomcat-migraion-tool to rebuild shiro jar（https://tomcat.apache.org/download-migration.cgi），
solved the compilation problem of my project, but there is a runtime error.

```
2023-06-12 16:01:51.512[][ERROR][http-nio-8081-exec-9][org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]:175]Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Servlet execution threw an exception] with root causejava.lang.ClassNotFoundException: jakarta.servlet.http.HttpSessionContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.apache.shiro.web.servlet.ShiroHttpServletRequest.getSession(ShiroHttpServletRequest.java:159)
	at org.springframework.web.util.WebUtils.getSessionId(WebUtils.java:360)
	at org.springframework.web.servlet.FrameworkServlet.publishRequestHandledEvent(FrameworkServlet.java:1149)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1028)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
```

I check the code. HttpSessionContext has been removed by Jakarta Servlet6.0 (jakarta ee10), so an error is reported.

**Comment by lprimak** [comment]
I created https://github.com/flowlogix/shiro-springboot3-demo which works with the upcoming Shiro 2.0.0-alpha-3 or later

**Comment by lprimak** [comment]
Once Shiro 2-alpha-3 is released, please use https://github.com/flowlogix/shiro-springboot3-demo as example code with SpringBoot 3 and above

**Comment by lprimak** [comment]
I also created a new example in Shiro: https://github.com/apache/shiro/tree/main/samples/spring-boot-3-web that uses Spring Boot 3

**Comment by scbant** [comment]
@damingerdai @house0128 @sam2099 

Try it like:

```
dependencies {
    ...
    implementation('org.apache.shiro:shiro-spring:1.11.0:jakarta') { exclude group: 'org.apache.shiro', module: 'shiro-web' }
    implementation 'org.apache.shiro:shiro-web:1.11.0:jakarta'
    ...
}
```

Work for Gradle7.4.1 and SpringBoot3.

**Comment by damingerdai** [comment]
@scbant  thanks

**Comment by esotericman** [comment]
But `shiro-spring` sources jar still use wrong namespace, 
![Screenshot from 2023-11-16 14-48-51](https://github.com/apache/shiro/assets/47545727/676b1a99-f3ce-4ec0-893d-c16169d779f1)
When we try to download source, getting puzzle... Anyway, The class file with correct jakarta namesapce

**Comment by scbant** [comment]
@esotericman https://github.com/apache/shiro/issues/891#issuecomment-1813883704

Make sure your Gradle dependencies config is same as https://github.com/apache/shiro/issues/891#issuecomment-1628430612.

Clean Gradle cache and rebuild.
