### ISSUE TITLE
shiro-spring 1.9.x Spring circular reference exception

### ISSUE THREAD

**Issue by JamesGosl** [apache/shiro#910]
**Version Shiro 1.9.x**

- 在使用samples-spring-mvc 模块学习shiro-spring 的过程中，发现始终运行不起来，Spring 会有一个循环依赖无法解决的错误 (如下图所示)

![image](https://github.com/apache/shiro/assets/52338323/dc78e68b-7c3e-4a67-ad90-722d4cfd98bc)

- 经过排查发现，这个问题出现在`org.apache.shiro.spring.web.ShiroFilterFactoryBean` 上
- 在shiro-spring 1.8.x 版本中 `org.apache.shiro.spring.web.ShiroFilterFactoryBean` 实现的两个接口是`org.springframework.beans.factory.FactoryBean` 和`org.springframework.beans.factory.config.BeanPostProcessor`
- 在shiro-spring 1.8.x 版本中 `org.apache.shiro.spring.web.ShiroFilterFactoryBean` 实现的`org.springframework.beans.factory.FactoryBean` 接口增加了泛型 (如下图所示)

![image](https://github.com/apache/shiro/assets/52338323/66a064b8-78e6-41aa-81a9-ff495073edc5)

- 造成这个问题的原因，因太过复杂 不对其进行解释 (自行查看阅读Spring 源码来理解)

**Comment by lprimak** [comment]
Does this issue exist in Shiro 1.11 or 2.0-alpha?
Disclaimer: I am not spring user and just trying to help out

**Comment by JamesGosl** [comment]
Shiro 1.8.x and subsequent versions will have this issue.
My solution is to remove the generics in the following code.
`support/spring/src/main/java/org/apache/shiro/spring/web/ShiroFilterFactoryBean.java`


![image](https://github.com/apache/shiro/assets/52338323/3c7fa1ec-e34b-4363-83b5-b1fc024077de)

**Comment by lprimak** [comment]
Have you actually tested it with 1.11? Latest Spring version as well?
For all I know this could be a bug in Spring
